[package]
name = "lino"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.9"
reqwest = "0.11.12"
shellexpand = "2.1.2"
tokio = { version = "1.21.2", features = ["full"] }
